# SPDX-FileCopyrightText: 2025 AftrLite
#
# SPDX-License-Identifier: LicenseRef-Wallening

# ROLE STARTING GEAR
- type: startingGear
  id: StellarGearCommandHeadOfSecurity
  equipment:
    shoes: StellarClothingShoesMiscBlackDress
    eyes: StellarClothingEyesMiscCommandGlasses
    id: StellarPDACommandHeadOfSecurity
    ears: StellarClothingHeadsetHeadOfSecurity
  storage:
    back:
    - Flash



# ROLE LOADOUT CONFIG
- type: roleLoadout
  id: StellarJobCommandHeadOfSecurity
  groups:
  # - StellarHeadOfSecurityNeck
  - StellarHeadOfSecurityUniform
  # - StellarHeadOfSecurityOuterClothing
  - StellarHeadOfSecurityBackpack
  - Survival
  - GroupSpeciesBreathTool
  - GroupTankHarness


# LOADOUT GROUPS
- type: loadoutGroup
  id: StellarHeadOfSecurityUniform
  name: stellar-loadout-uniform
  loadouts:
  - StellarHeadOfSecurityUniform
  - StellarHeadOfSecurityUniformSkirt
  - StellarHeadOfSecurityUniformCasual
  - StellarHeadOfSecurityUniformCasualSkirt
  - StellarHeadOfSecurityUniformFormal
  - StellarHeadOfSecurityUniformParade

- type: loadoutGroup
  id: StellarHeadOfSecurityBackpack
  name: stellar-loadout-backpack
  loadouts:
  - StellarHeadOfSecurityBackpack



# LOADOUT GROUP CONTENTS

### HEAD


### UNIFORM
- type: loadout
  id: StellarHeadOfSecurityUniform
  equipment:
    jumpsuit: StellarClothingUniformCommandHeadOfSecurity
  groupBy: "uniform"

- type: loadout
  id: StellarHeadOfSecurityUniformSkirt
  equipment:
    jumpsuit: StellarClothingUniformCommandHeadOfSecuritySkirt
  groupBy: "uniform-skirt"

- type: loadout
  id: StellarHeadOfSecurityUniformCasual
  equipment:
    jumpsuit: StellarClothingUniformCommandHeadOfSecurityAlt
  groupBy: "uniform"

- type: loadout
  id: StellarHeadOfSecurityUniformCasualSkirt
  equipment:
    jumpsuit: StellarClothingUniformCommandHeadOfSecurityAltSkirt
  groupBy: "uniform-skirt"

- type: loadout
  id: StellarHeadOfSecurityUniformFormal
  equipment:
    jumpsuit: StellarClothingUniformCommandHeadOfSecurityFormal
  groupBy: "uniform"

- type: loadout
  id: StellarHeadOfSecurityUniformParade
  equipment:
    jumpsuit: StellarClothingUniformCommandHeadOfSecurityParade
  groupBy: "uniform"

### BACKPACK
- type: loadout
  id: StellarHeadOfSecurityBackpack
  equipment:
    back: StellarClothingBackpackCommandHeadOfSecurity
